# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: df3697aff50548f95c26b2d2f07ce9e884b15f388ac47e73c0c4dc6341c35a7eba5ce3dd95f418c811a5a6d89eb9ed173de165eaf9176cf73678f13f6d3f8f70

test:
  secret_key_base: 69b97c5a0c3b732ed3c7b01f55f00084b16343a527e3a8552df74ddf67386b584e0b9c2f13fb16c4c090f8a58c81ac09b42855ef703853c6442a4be0bfeb8eff

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
